/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RefPoint = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Float64,
  'tenor' : IDL.Text,
  'title' : IDL.Text,
  'endTime' : IDL.Float64,
  'bass' : IDL.Text,
  'description' : IDL.Text,
  'chords' : IDL.Text,
  'harmonicAnalysis' : IDL.Text,
  'keySignature' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'bpm' : IDL.Nat,
  'owner' : IDL.Principal,
  'refPoints' : IDL.Vec(RefPoint),
  'name' : IDL.Text,
  'polarity' : IDL.Bool,
  'musicalKey' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'renameProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text, IDL.Vec(RefPoint)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RefPoint = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Float64,
    'tenor' : IDL.Text,
    'title' : IDL.Text,
    'endTime' : IDL.Float64,
    'bass' : IDL.Text,
    'description' : IDL.Text,
    'chords' : IDL.Text,
    'harmonicAnalysis' : IDL.Text,
    'keySignature' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'bpm' : IDL.Nat,
    'owner' : IDL.Principal,
    'refPoints' : IDL.Vec(RefPoint),
    'name' : IDL.Text,
    'polarity' : IDL.Bool,
    'musicalKey' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'renameProject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text, IDL.Vec(RefPoint)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };