/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BrandingSettings {
    theme: string;
    font: string;
    logoUrl: string;
}
export interface UserProfile {
    name: string;
    avatar?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RefPoint {
    id: string;
    startTime: number;
    tenor: string;
    title: string;
    endTime: number;
    bass: string;
    description: string;
    chords: string;
    harmonicAnalysis: string;
    keySignature: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Template {
    id: string;
    bpm: bigint;
    backgroundSettings: BackgroundSettings;
    refPoints: Array<RefPoint>;
    name: string;
    description: string;
    polarity: boolean;
    image?: ExternalBlob;
    musicalKey: string;
    brandingSettings: BrandingSettings;
    tunnelSettings: TunnelSettings;
}
export interface ProjectStatistics {
    projectsPerUser: Array<[Principal, bigint]>;
    totalProjects: bigint;
    averageBpm: number;
    mostCommonKey: string;
    polarityCount: bigint;
}
export interface BackgroundSettings {
    color: string;
    brightness: number;
    style: string;
}
export interface TunnelSettings {
    complexity: bigint;
    rotation: boolean;
    mode: string;
    speed: number;
    depth: number;
}
export interface ProjectFilters {
    bpmRange?: [bigint, bigint];
    owner?: Principal;
    keyword?: string;
}
export interface Project {
    id: string;
    bpm: bigint;
    backgroundSettings: BackgroundSettings;
    owner: Principal;
    refPoints: Array<RefPoint>;
    published: boolean;
    name: string;
    polarity: boolean;
    isShared: boolean;
    image?: ExternalBlob;
    musicalKey: string;
    brandingSettings: BrandingSettings;
    tunnelSettings: TunnelSettings;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ProjectSummary {
    id: string;
    bpm: bigint;
    owner: Principal;
    published: boolean;
    name: string;
    isShared: boolean;
    image?: ExternalBlob;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTemplate(name: string, description: string, polarity: boolean, bpm: bigint, musicalKey: string, backgroundSettings: BackgroundSettings, brandingSettings: BrandingSettings, tunnelSettings: TunnelSettings, image: ExternalBlob | null): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProject(name: string, polarity: boolean, bpm: bigint, musicalKey: string, backgroundSettings: BackgroundSettings, brandingSettings: BrandingSettings, tunnelSettings: TunnelSettings, image: ExternalBlob | null, published: boolean, isShared: boolean): Promise<string>;
    deleteProject(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProject(id: string): Promise<Project>;
    getProjectStatistics(): Promise<ProjectStatistics>;
    getPublishedProjects(limit: bigint, offset: bigint): Promise<Array<ProjectSummary>>;
    getShareToken(projectId: string): Promise<string | null>;
    getSharedProjectIfPublished(projectId: string): Promise<Project>;
    getSharedProjects(limit: bigint, offset: bigint): Promise<Array<ProjectSummary>>;
    getTemplates(limit: bigint, offset: bigint): Promise<Array<Template>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listProjects(filters: ProjectFilters, limit: bigint, offset: bigint): Promise<Array<ProjectSummary>>;
    renameProject(id: string, newName: string): Promise<void>;
    saveCallerUserProfile(name: string, avatar: ExternalBlob | null): Promise<void>;
    updateBackgroundSettings(projectId: string, newSettings: BackgroundSettings): Promise<void>;
    updateBrandingSettings(projectId: string, newSettings: BrandingSettings): Promise<void>;
    updateProject(id: string, name: string, polarity: boolean, bpm: bigint, musicalKey: string, refPoints: Array<RefPoint>, backgroundSettings: BackgroundSettings, brandingSettings: BrandingSettings, tunnelSettings: TunnelSettings, image: ExternalBlob | null, published: boolean, isShared: boolean): Promise<void>;
    updateTunnelSettings(projectId: string, newSettings: TunnelSettings): Promise<void>;
}
import type { BackgroundSettings as _BackgroundSettings, BrandingSettings as _BrandingSettings, ExternalBlob as _ExternalBlob, Project as _Project, ProjectFilters as _ProjectFilters, ProjectSummary as _ProjectSummary, RefPoint as _RefPoint, Template as _Template, TunnelSettings as _TunnelSettings, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTemplate(arg0: string, arg1: string, arg2: boolean, arg3: bigint, arg4: string, arg5: BackgroundSettings, arg6: BrandingSettings, arg7: TunnelSettings, arg8: ExternalBlob | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTemplate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTemplate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: string, arg1: boolean, arg2: bigint, arg3: string, arg4: BackgroundSettings, arg5: BrandingSettings, arg6: TunnelSettings, arg7: ExternalBlob | null, arg8: boolean, arg9: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_Project_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_Project_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectStatistics(): Promise<ProjectStatistics> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectStatistics();
            return result;
        }
    }
    async getPublishedProjects(arg0: bigint, arg1: bigint): Promise<Array<ProjectSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedProjects(arg0, arg1);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedProjects(arg0, arg1);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShareToken(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareToken(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareToken(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedProjectIfPublished(arg0: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedProjectIfPublished(arg0);
                return from_candid_Project_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedProjectIfPublished(arg0);
            return from_candid_Project_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedProjects(arg0: bigint, arg1: bigint): Promise<Array<ProjectSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedProjects(arg0, arg1);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedProjects(arg0, arg1);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplates(arg0: bigint, arg1: bigint): Promise<Array<Template>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplates(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplates(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listProjects(arg0: ProjectFilters, arg1: bigint, arg2: bigint): Promise<Array<ProjectSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects(to_candid_ProjectFilters_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects(to_candid_ProjectFilters_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameProject(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameProject(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBackgroundSettings(arg0: string, arg1: BackgroundSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBackgroundSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBackgroundSettings(arg0, arg1);
            return result;
        }
    }
    async updateBrandingSettings(arg0: string, arg1: BrandingSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrandingSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrandingSettings(arg0, arg1);
            return result;
        }
    }
    async updateProject(arg0: string, arg1: string, arg2: boolean, arg3: bigint, arg4: string, arg5: Array<RefPoint>, arg6: BackgroundSettings, arg7: BrandingSettings, arg8: TunnelSettings, arg9: ExternalBlob | null, arg10: boolean, arg11: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg9), arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg9), arg10, arg11);
            return result;
        }
    }
    async updateTunnelSettings(arg0: string, arg1: TunnelSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTunnelSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTunnelSettings(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ProjectSummary_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectSummary): Promise<ProjectSummary> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Project_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Promise<Project> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Template_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Template): Promise<Template> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    avatar?: ExternalBlob;
}> {
    return {
        name: value.name,
        avatar: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bpm: bigint;
    backgroundSettings: _BackgroundSettings;
    owner: Principal;
    refPoints: Array<_RefPoint>;
    published: boolean;
    name: string;
    polarity: boolean;
    isShared: boolean;
    image: [] | [_ExternalBlob];
    musicalKey: string;
    brandingSettings: _BrandingSettings;
    tunnelSettings: _TunnelSettings;
}): Promise<{
    id: string;
    bpm: bigint;
    backgroundSettings: BackgroundSettings;
    owner: Principal;
    refPoints: Array<RefPoint>;
    published: boolean;
    name: string;
    polarity: boolean;
    isShared: boolean;
    image?: ExternalBlob;
    musicalKey: string;
    brandingSettings: BrandingSettings;
    tunnelSettings: TunnelSettings;
}> {
    return {
        id: value.id,
        bpm: value.bpm,
        backgroundSettings: value.backgroundSettings,
        owner: value.owner,
        refPoints: value.refPoints,
        published: value.published,
        name: value.name,
        polarity: value.polarity,
        isShared: value.isShared,
        image: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.image)),
        musicalKey: value.musicalKey,
        brandingSettings: value.brandingSettings,
        tunnelSettings: value.tunnelSettings
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bpm: bigint;
    owner: Principal;
    published: boolean;
    name: string;
    isShared: boolean;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    bpm: bigint;
    owner: Principal;
    published: boolean;
    name: string;
    isShared: boolean;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        bpm: value.bpm,
        owner: value.owner,
        published: value.published,
        name: value.name,
        isShared: value.isShared,
        image: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bpm: bigint;
    backgroundSettings: _BackgroundSettings;
    refPoints: Array<_RefPoint>;
    name: string;
    description: string;
    polarity: boolean;
    image: [] | [_ExternalBlob];
    musicalKey: string;
    brandingSettings: _BrandingSettings;
    tunnelSettings: _TunnelSettings;
}): Promise<{
    id: string;
    bpm: bigint;
    backgroundSettings: BackgroundSettings;
    refPoints: Array<RefPoint>;
    name: string;
    description: string;
    polarity: boolean;
    image?: ExternalBlob;
    musicalKey: string;
    brandingSettings: BrandingSettings;
    tunnelSettings: TunnelSettings;
}> {
    return {
        id: value.id,
        bpm: value.bpm,
        backgroundSettings: value.backgroundSettings,
        refPoints: value.refPoints,
        name: value.name,
        description: value.description,
        polarity: value.polarity,
        image: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.image)),
        musicalKey: value.musicalKey,
        brandingSettings: value.brandingSettings,
        tunnelSettings: value.tunnelSettings
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectSummary>): Promise<Array<ProjectSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ProjectSummary_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Template>): Promise<Array<Template>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Template_n26(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ProjectFilters_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectFilters): _ProjectFilters {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bpmRange?: [bigint, bigint];
    owner?: Principal;
    keyword?: string;
}): {
    bpmRange: [] | [[bigint, bigint]];
    owner: [] | [Principal];
    keyword: [] | [string];
} {
    return {
        bpmRange: value.bpmRange ? candid_some(value.bpmRange) : candid_none(),
        owner: value.owner ? candid_some(value.owner) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
